#!/bin/bash

set -e 
YELLOW='\033[1;33m'
GREEN='\033[1;32m'
NC='\033[0m'

mkdir -p ~/.vim/autoload ~/.vim/bundle ~/.vim/colors

#Install the pathogen plugin manager
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

#Installing plugins
git clone https://github.com/scrooloose/nerdtree.git ~/.vim/bundle/nerdtree
git clone https://github.com/jistr/vim-nerdtree-tabs.git ~/.vim/bundle/vim-nerdtree-tabs
git clone https://github.com/itchyny/lightline.vim ~/.vim/bundle/lightline.vim

#Install the peaksea colour scheme
wget -q --show-progress https://raw.githubusercontent.com/vim-scripts/peaksea/master/colors/peaksea.vim -P ~/.vim/colors

#Copy vimrc contents into ~/.vimrc
cat vimrc > ~/.vimrc

echo -e "\n${GREEN}VIM-IDE has been successfully installed${NC}"
